# Generated by Django 3.0.6 on 2020-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200531_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price_small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
