# Generated by Django 3.0.6 on 2020-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ordercounter_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercounter',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
